/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -T Amy.glb
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import AmyModel from '../../models/Amy.glb';
import { usePrevious } from '../../hooks/usePrevious';

export function Amy(props) {
  const { activeAction } = props;
  const group = useRef();
  const previousAction = usePrevious(activeAction);
  const { nodes, materials, animations } = useGLTF(AmyModel);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (previousAction) {
      actions[previousAction].fadeOut(0.1);
      actions[activeAction].reset().fadeIn(0.1).play();
    }
    actions[activeAction].reset().fadeIn(0.1).play();
  }, [activeAction, actions, previousAction]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="Ch46"
            geometry={nodes.Ch46.geometry}
            material={materials.Ch46_body}
            skeleton={nodes.Ch46.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(AmyModel);
