/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -T StringLights.glb
Author: m31odyr (https://sketchfab.com/m31odyr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/emissive-orange-and-redr-string-lights-94cee5bd1abf4960a5a9a22d4cbda24b
Title: Emissive orange and redr string lights
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import StringLightsModel from '../../assets/models/StringLights.glb';

export function StringLights(props) {
  const { nodes, materials } = useGLTF(StringLightsModel);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.pTorus2_initialShadingGroup_0.geometry}
        material={materials.initialShadingGroup}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload(StringLightsModel);
