/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -T Dart.glb
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import DartModel from '../models/Dart.glb';

export function Dart(props) {
  const { nodes, materials } = useGLTF(DartModel);
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat23} />
      <mesh
        geometry={nodes['Node-Mesh_1'].geometry}
        material={materials.mat10}
      />
      <mesh
        geometry={nodes['Node-Mesh_2'].geometry}
        material={materials.mat8}
      />
      <mesh
        geometry={nodes['Node-Mesh_3'].geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes['Node-Mesh_4'].geometry}
        material={materials.mat19}
      />
      <mesh
        geometry={nodes['Node-Mesh_5'].geometry}
        material={materials.mat12}
      />
      <mesh
        geometry={nodes['Node-Mesh_6'].geometry}
        material={materials.mat22}
      />
    </group>
  );
}

useGLTF.preload(DartModel);
