/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -T Jenga.glb
Author: Rukh3D (https://sketchfab.com/rukh3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jenga-wooden-blocks-game-c53bf27acdd94adaa78ff9019029ba05
Title: Jenga Wooden Blocks Game
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import JengaModel from '../models/Jenga.glb';

export function Jenga(props) {
  const { nodes, materials } = useGLTF(JengaModel);
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.pCube3014_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 10.27, -1.77]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3001_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 0.39, -1.56]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3002_blocks_0.geometry}
          material={materials.blocks}
          position={[-1.64, 1.1, -0.13]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3003_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 1.81, -1.56]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3004_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 3.22, -1.61]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3005_blocks_0.geometry}
          material={materials.blocks}
          position={[-1.64, 3.92, -0.13]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3006_blocks_0.geometry}
          material={materials.blocks}
          position={[-1.64, 5.33, -0.13]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3007_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 6.04, -1.56]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3008_blocks_0.geometry}
          material={materials.blocks}
          position={[-1.64, 6.74, -0.13]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3009_blocks_0.geometry}
          material={materials.blocks}
          position={[-1.64, 8.15, -0.13]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3010_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 8.86, -1.77]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3011_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 0.39, 0.09]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3012_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 2.51, 0.09]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3013_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 3.92, 0.09]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3015_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 4.63, 0.09]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3016_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 5.33, -0.13]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3017_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 6.04, 0.02]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3018_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 7.45, -0.13]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3019_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 8.15, 0.09]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3020_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 8.86, -0.13]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3021_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 9.56, 0.09]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3022_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 10.27, -0.13]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3023_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 0.39, 1.73]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3024_blocks_0.geometry}
          material={materials.blocks}
          position={[1.64, 1.1, 0.09]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3025_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 1.81, 1.52]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3026_blocks_0.geometry}
          material={materials.blocks}
          position={[1.64, 2.51, 0.09]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3027_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 3.22, 1.52]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3028_blocks_0.geometry}
          material={materials.blocks}
          position={[1.64, 3.92, 0.09]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3029_blocks_0.geometry}
          material={materials.blocks}
          position={[1.64, 5.33, 0.09]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3030_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 6.04, 1.73]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3031_blocks_0.geometry}
          material={materials.blocks}
          position={[1.64, 6.74, 0.09]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3032_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 7.45, 1.52]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3033_blocks_0.geometry}
          material={materials.blocks}
          position={[1.64, 8.15, -0.13]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3034_blocks_0.geometry}
          material={materials.blocks}
          position={[0, 8.86, 1.52]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3035_blocks_0.geometry}
          material={materials.blocks}
          position={[1.64, 9.56, -0.13]}
          scale={[1.38, 1, 1.61]}
        />
        <mesh
          geometry={nodes.pCube3036_blocks_0.geometry}
          material={materials.blocks}
          position={[0.17, 10.27, 1.61]}
          scale={[1.38, 1, 1.61]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(JengaModel);
