/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -T Stool.glb
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import StoolModel from '../models/Stool.glb';

export function Stool(props) {
  const { nodes, materials } = useGLTF(StoolModel);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Stool_Circle014.geometry}
        material={materials['795548']}
      />
    </group>
  );
}

useGLTF.preload(StoolModel);
