/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -T Table.glb
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import TableModel from '../models/Table.glb';

export function Table(props) {
  const { nodes, materials } = useGLTF(TableModel);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Table_Large_Rectangular_01_Circle004.geometry}
        material={materials['795548']}
      />
    </group>
  );
}

useGLTF.preload(TableModel);
