/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -T Trampoline.glb
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import TrampolineModel from '../models/Trampoline.glb';

export function Trampoline(props) {
  const { nodes, materials } = useGLTF(TrampolineModel);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Trampoline_Mesh.geometry}
        material={materials.Trampoline_Mat}
      />
    </group>
  );
}

useGLTF.preload(TrampolineModel);
