/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -T ./BistroSet.glb
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import BistroSetModel from '../models/BistroSet.glb';

export function BistroSet(props) {
  const { nodes, materials } = useGLTF(BistroSetModel);
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.Basic} />
      <mesh
        geometry={nodes['Node-Mesh_1'].geometry}
        material={materials.Basic}
      />
      <mesh
        geometry={nodes['Node-Mesh_2'].geometry}
        material={materials.Seat_Cush1_1}
      />
      <mesh
        geometry={nodes['Node-Mesh_3'].geometry}
        material={materials.Basic}
      />
      <mesh
        geometry={nodes['Node-Mesh_4'].geometry}
        material={materials.Seat_Cush1_1}
      />
      <mesh
        geometry={nodes['Node-Mesh_5'].geometry}
        material={materials.Basic}
      />
      <mesh
        geometry={nodes['Node-Mesh_6'].geometry}
        material={materials.Seat_Cush1_1}
      />
      <mesh
        geometry={nodes['Node-Mesh_7'].geometry}
        material={materials.Basic}
      />
      <mesh
        geometry={nodes['Node-Mesh_8'].geometry}
        material={materials.Seat_Cush1_1}
      />
    </group>
  );
}

useGLTF.preload(BistroSetModel);
