/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -T ./CandyStall.glb
Author: leha_pu (https://sketchfab.com/leha_pu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/candy-stall-d5dcda59348d4a91a0c5835b5f443d7d
Title: Candy stall
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import CandyStallModel from '../models/CandyStall.glb';

export function CandyStall(props) {
  const { nodes, materials } = useGLTF(CandyStallModel);
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.Cube099_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[36.05, 207.36, -0.62]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube100_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-20.37, 270.41, -0.62]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube101_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[34.87, 172.11, -0.62]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube102_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[35.31, 44.12, -0.19]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube103_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-32.45, 231.76, 90.03]}
          rotation={[-Math.PI / 2, 0, -1.67]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube104_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[117.48, 174.1, -0.62]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube105_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-38, 85.09, 96.59]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Circle001_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-42, 298.48, 8.08]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Plane001_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-36.47, 322.36, 8.08]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube106_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-47.57, 325.23, -52.38]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube107_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[22.13, 241, -0.62]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube108_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[10.04, 202.36, 90.03]}
          rotation={[-Math.PI / 2, 0, -1.67]}
          scale={100}
        />
        <mesh
          geometry={nodes.BezierCurve001_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[115.65, 174.1, -0.62]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={100}
        />
        <mesh
          geometry={nodes.Text001_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-34.06, 324.24, 8.08]}
          rotation={[0, Math.PI / 2, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube134_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[21.03, 244.92, 78.04]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube135_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[18.86, 276.9, 83.96]}
          rotation={[-1.43, 0, 0]}
          scale={63.6}
        />
        <mesh
          geometry={nodes.Cube136_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[75.41, 239.96, 90.87]}
          rotation={[-0.28, -0.25, 1.53]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube137_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[24.47, 291.52, 54.19]}
          rotation={[-1.4, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube138_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[96.61, 239.56, 90.68]}
          rotation={[-1.22, 0.91, 2.67]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube139_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[86.3, 247.51, 96.86]}
          rotation={[-1.26, -0.04, 1.67]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube140_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[19.79, 276.9, 71.42]}
          rotation={[-1.68, -0.09, -2.46]}
          scale={63.6}
        />
        <mesh
          geometry={nodes.Cube141_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[27.44, 276.9, 80.43]}
          rotation={[-1.51, 0.12, 2.18]}
          scale={63.6}
        />
        <mesh
          geometry={nodes.Cube142_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[26.63, 244.92, 47.21]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={150.39}
        />
        <mesh
          geometry={nodes.Cube143_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[32.94, 274.37, 47.82]}
          rotation={[-1.67, 0.13, 2.22]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube144_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[23.73, 279.87, 42.44]}
          rotation={[-1.74, -0.13, -3.12]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube145_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[76.09, 217.2, 61.56]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube146_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[82.88, 225.42, 70.6]}
          rotation={[0, -0.68, -Math.PI / 2]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube147_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[55.8, 245.68, 89.52]}
          rotation={[-0.6, -0.67, -0.4]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube148_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[63.82, 234.14, 27.51]}
          rotation={[-2.16, -0.33, 0.46]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube149_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[79.62, 226.73, 41.26]}
          rotation={[-2.82, 0.51, -1.73]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube150_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[73.48, 231.21, 51.36]}
          rotation={[-0.73, 0.85, 0.6]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube151_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[86.22, 219.63, 49.02]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube152_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[61.46, 224.71, 59.31]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube153_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[69.3, 235.98, 38.79]}
          rotation={[-2.22, -0.17, -0.82]}
          scale={83.93}
        />
        <mesh
          geometry={nodes.Cube154_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-18.49, 274.25, -74.53]}
          rotation={[-Math.PI / 2, 0, -2.46]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube155_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-13.91, 287.44, -84.57]}
          rotation={[-0.34, -0.72, -1.8]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube156_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-25.82, 288.59, -83.99]}
          rotation={[-0.42, 0.72, -1.28]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube157_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-16.3, 288.29, -76.98]}
          rotation={[1.57, 0.65, -3.14]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube158_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-10.92, 286.93, -81.17]}
          rotation={[-0.75, -0.7, -2.11]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube159_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-12.11, 288.4, -73.86]}
          rotation={[0.58, 0, -1.57]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube160_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-28.74, 288.73, -77.57]}
          rotation={[-1.27, 1.12, -0.33]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube161_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-25.38, 286.43, -70]}
          rotation={[0, 0.34, -1.24]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube162_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-19.06, 287.51, -69.64]}
          rotation={[2.45, 0.49, 1.94]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube163_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-14.6, 288.76, -67.51]}
          rotation={[0.73, 0, -Math.PI / 2]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube164_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-8.2, 288.41, -68.69]}
          rotation={[0.51, 0.87, -1.98]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube165_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-21.24, 288.26, -79.07]}
          rotation={[1.16, -0.08, -1.39]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube166_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[23.41, 244.73, -50.8]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube167_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[64.02, 217.2, -81.51]}
          rotation={[-Math.PI / 2, 0, 0.28]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube168_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[81.27, 217.2, -17.72]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube169_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[83.87, 225, -4.28]}
          rotation={[-Math.PI / 2, -0.25, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube170_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[88.03, 227.74, -19.54]}
          rotation={[-Math.PI / 2, -0.25, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube171_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[83.87, 225, -32.91]}
          rotation={[-1.15, -0.24, 0.34]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube172_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[70.46, 228.38, -20.03]}
          rotation={[-1.53, -0.27, 1.74]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube173_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[96.24, 234.87, -8.25]}
          rotation={[-1.6, -0.03, -0.91]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube174_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[60.93, 224.3, -93.09]}
          rotation={[-1.32, 0.05, -1.38]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube175_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[89.02, 236.84, -2.4]}
          rotation={[-1.21, -0.5, 0.68]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube176_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[18.12, 250.36, -69.21]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={50.34}
        />
        <mesh
          geometry={nodes.Cube177_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[29.95, 250.19, -77.59]}
          rotation={[-Math.PI / 2, 0, 1.5]}
          scale={50.34}
        />
        <mesh
          geometry={nodes.Cube178_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[19.1, 251.75, -57.82]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={50.34}
        />
        <mesh
          geometry={nodes.Cube179_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[15.7, 252.23, -45.56]}
          rotation={[-Math.PI / 2, 0, 2.47]}
          scale={50.34}
        />
        <mesh
          geometry={nodes.Cube180_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[20.45, 249.78, -32.51]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={50.34}
        />
        <mesh
          geometry={nodes.Cube181_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[19.86, 250.41, -18.1]}
          rotation={[-1.76, -0.21, -0.72]}
          scale={50.34}
        />
        <mesh
          geometry={nodes.Cube182_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[91.58, 217.2, -74.65]}
          rotation={[-Math.PI / 2, 0, 0.28]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube183_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[32.69, 250.19, -46.57]}
          rotation={[-Math.PI / 2, 0, -0.01]}
          scale={50.34}
        />
        <mesh
          geometry={nodes.Cube184_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[36.01, 249.78, -32.51]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={50.34}
        />
        <mesh
          geometry={nodes.Cube185_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[30.2, 249.78, -58.83]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={50.34}
        />
        <mesh
          geometry={nodes.Cube186_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[32.63, 252.23, -69.01]}
          rotation={[-Math.PI / 2, 0, 1.04]}
          scale={50.34}
        />
        <mesh
          geometry={nodes.Cube187_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[27.83, 251.79, -26.23]}
          rotation={[-1.5, 0.08, -0.73]}
          scale={50.34}
        />
        <mesh
          geometry={nodes.Cube188_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[24.88, 250.13, -48.08]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={50.34}
        />
        <mesh
          geometry={nodes.Cube189_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[11.81, 251.68, -35.5]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={50.34}
        />
        <mesh
          geometry={nodes.Cube190_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[14.82, 253.69, -25]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={50.34}
        />
        <mesh
          geometry={nodes.Cube191_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[40.94, 250.14, -40.55]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={50.34}
        />
        <mesh
          geometry={nodes.Cube192_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[35.91, 253.83, -60.12]}
          rotation={[-1.8, 0.5, 0.45]}
          scale={50.34}
        />
        <mesh
          geometry={nodes.Cube193_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[18.62, 251.73, -76.93]}
          rotation={[-2.41, 0, 0]}
          scale={50.34}
        />
        <mesh
          geometry={nodes.Cube194_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[11.37, 251.92, -55.33]}
          rotation={[-1.3, -0.81, 1.94]}
          scale={50.34}
        />
        <mesh
          geometry={nodes.Cube195_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[66.06, 224.3, -77.59]}
          rotation={[-1.32, 0.06, -1.35]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube196_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[87.49, 224.3, -87.38]}
          rotation={[-1.33, 0.07, -1.29]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube197_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[90.71, 224.3, -70.68]}
          rotation={[-1.36, 0.14, -0.98]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube109_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[-19.02, 286.06, 84.13]}
          rotation={[Math.PI, -1.07, -Math.PI / 2]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube110_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[8.85, 67.44, 60.77]}
          rotation={[-Math.PI / 2, 0, 1.28]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube112_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[46.32, 79.62, -39.35]}
          rotation={[-Math.PI / 2, 0, 0.13]}
          scale={100}
        />
        <mesh
          geometry={nodes.Cube111_DefaultMaterial_0.geometry}
          material={materials.DefaultMaterial}
          position={[53.27, 67.44, 60.36]}
          rotation={[-Math.PI / 2, 0, 1.56]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload(CandyStallModel);
