/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -T ./CrossTable.glb
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import CrossTableModel from '../models/CrossTable.glb';

export function CrossTable(props) {
  const { nodes, materials } = useGLTF(CrossTableModel);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.tableCrossCloth_2.geometry}
        material={materials.wood}
      />
      <mesh
        geometry={nodes.tableCrossCloth_2_1.geometry}
        material={materials.carpet}
      />
      <mesh
        geometry={nodes.tableCrossCloth_3.geometry}
        material={materials.carpet}
      />
      <mesh
        geometry={nodes.tableCrossCloth_3_1.geometry}
        material={materials.wood}
      />
    </group>
  );
}

useGLTF.preload(CrossTableModel);
